server:
  port: ${port:8761}

spring:
  application:
    name: eureka-naming-server
  output:
    ansi:
      enabled: ALWAYS

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false