server:
  port: ${port:8300}

spring:
  application:
    name: product-enquiry-service
  output:
    ansi:
      enabled: ALWAYS
  cloud:
    loadbalancer:
      ribbon:
        enable: false

#product-stock-service:
#  ribbon:
#    listOfServers: http://localhost:8200, http://localhost:8201



