server:
  port: ${port:8300}

spring:
  application:
    name: product-enquiry-service
  output:
    ansi:
      enabled: ALWAYS
#  h2:
#    console:
#      enabled: true
#  jpa:
#    show-sql: true
#    database-platform: org.hibernate.dialect.H2Dialect
#  datasource:
#    url: jdbc:h2:mem:testdb
#    driverClassName: org.h2.Driver
#    username: sa
#    password:
