server:
  port: ${port:8762}

spring:
  application:
    name: zuul-api-gateway-server
  output:
    ansi:
      enabled: ALWAYS

zuul:
  routes:
    product-enquiry: /product-enquiry/**
    url: http://localhost:8300/