server:
  port: ${port:8200}

spring:
  application:
    name: product-stock-service
  output:
    ansi:
      enabled: ALWAYS
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    database-platform: org.hibernate.dialect.H2Dialect
  datasource:
    url: jdbc:h2:mem:testdb
    driverClassName: org.h2.Driver
    username: sa
    password:
