server:
  port: ${port:8888}
spring:
  application:
    name: spring-cloud-config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/poik12/microservices-demo-2.git
  output:
    ansi:
      enabled: ALWAYS