server:
  port: ${port:8100}

spring:
  application:
    name: property-access-service
  profiles:
    active: dev
  output:
    ansi:
      enabled: ALWAYS

management:
  endpoints:
    web:
      exposure:
        include: refresh